apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korp-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korp-operator-role
subjects:
  - kind: ServiceAccount
    name: korp-operator
    namespace: korp-operator
