apiVersion: korp.io/v1alpha1
kind: KorpScan
metadata:
  name: default-namespace-scan
  namespace: korp
spec:
  targetNamespace: "default"
  intervalMinutes: 30
  resourceTypes:
    - configmaps
    - secrets
    - pvcs
    - services
  reporting:
    createEvents: true
    eventSeverity: "Warning"
    historyLimit: 5
