apiVersion: v2
name: korp
description: A Helm chart for Korp - Kubernetes Orphaned Resource Pointer Operator
type: application
version: 0.2.0
appVersion: "v0.2.2"
keywords:
  - kubernetes
  - operator
  - orphaned-resources
  - cleanup
  - monitoring
home: https://github.com/kamilbabayev/korp
sources:
  - https://github.com/kamilbabayev/korp
maintainers:
  - name: Kamil Babayev
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
