{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "korp.fullname" . }}-default-sa
  labels:
    {{- include "korp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "korp.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ include "korp.namespace" . }}
{{- end }}
